name: mediashelf
services:
  db:
    build: ./docker/db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mediashelf
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./docker/app
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/var/www/html
 
  adminer:
    build: ./docker/adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata: